name: sneakers_track
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  sizer: ^2.0.15
  flow_builder: ^0.0.9
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  google_fonts: ^3.0.1
  firebase_auth: ^4.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0




flutter:
  uses-material-design: true

  assets:
    - assets/png/

#dependency_overrides:
    #bloc: ^8.1.0
    #bloc_test: ^9.1.0
    #flutter_bloc: ^8.1.1
