// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3oIpUL0NI9GsMs0b5vcWf6wLoqLQT22A',
    appId: '1:1042490983306:web:3793cd2bb1fbaa79c4be73',
    messagingSenderId: '1042490983306',
    projectId: 'sneakers-track',
    authDomain: 'sneakers-track.firebaseapp.com',
    storageBucket: 'sneakers-track.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0j5k7GzbiqXObFnmsomP2NqlBLV2-oQA',
    appId: '1:1042490983306:android:166c90b4ac381d5fc4be73',
    messagingSenderId: '1042490983306',
    projectId: 'sneakers-track',
    storageBucket: 'sneakers-track.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfBw-A83kEXOBoxK81euOH7-SAViosL1M',
    appId: '1:1042490983306:ios:a591f5709cb78f07c4be73',
    messagingSenderId: '1042490983306',
    projectId: 'sneakers-track',
    storageBucket: 'sneakers-track.appspot.com',
    iosClientId: '1042490983306-r7tfqj3g210aci450ifpedhiv2i58jr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sneakersTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfBw-A83kEXOBoxK81euOH7-SAViosL1M',
    appId: '1:1042490983306:ios:a591f5709cb78f07c4be73',
    messagingSenderId: '1042490983306',
    projectId: 'sneakers-track',
    storageBucket: 'sneakers-track.appspot.com',
    iosClientId: '1042490983306-r7tfqj3g210aci450ifpedhiv2i58jr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sneakersTrack',
  );
}
